USE sql_proj_inno;
-- ##1. Customer Insights

-- 1.1 How many unique customers have placed orders?
SELECT COUNT(DISTINCT cust_id) AS unique_customers
FROM orders;
-- 1.2 Which customers have placed the highest number of orders?
SELECT 
    c.cust_id,
    c.cust_name,
    COUNT(o.ord_id) AS total_orders
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_orders DESC LIMIT 1;
-- 1.3 What is the total and average purchase value per customer?
SELECT 
    c.cust_id,
    c.cust_name,
    SUM(od.total_price) AS total_purchase_value,
    AVG(od.total_price) AS average_purchase_value
FROM customers c
JOIN orders o 
    ON c.cust_id = o.cust_id
JOIN order_details od 
    ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name;
-- 1.4 Who are the top 5 customers by total purchase amount?
SELECT 
    c.cust_id,
    c.cust_name,
    SUM(od.total_price) AS total_purchase_value
FROM orders o 
JOIN order_details od 
    ON o.ord_id = od.ord_id
JOIN customers c
    ON c.cust_id = o.cust_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_purchase_value DESC LIMIT 5;

-- #2. Product Performance
-- 2.1 How many products exist in each category?
SELECT c.cat_id, c.cat_name,
COUNT(DISTINCT p.prod_name) AS Tota_Products
FROM products p
JOIN categories c 
USING (cat_id)
GROUP BY c.cat_id, c.cat_name;

-- 2.2 What is the average price of products by category?
SELECT cat_id, cat_name,AVG(price)
FROM products p
JOIN categories c 
USING(cat_id)
GROUP BY c.cat_id, c.cat_name;

-- 2.3 Which products have the highest total sales volume (by quantity)?
SELECT p.prod_id,p.prod_name, SUM(od.quantity) AS Total_sales
FROM products p
JOIN order_details od 
USING(prod_id)
GROUP BY p.prod_id,p.prod_name
ORDER BY Total_sales DESC
LIMIT 1;

-- 2.4 What is the total revenue generated by each product?
SELECT p.prod_name,SUM(od.total_price) AS total_revenue
FROM order_details od
JOIN products p 
USING(prod_id)
GROUP BY prod_name;

-- 2.5 How do product sales vary by category and supplier?
SELECT 
    c.cat_id,
    c.cat_name,
    s.sup_id,
    s.sup_name,
    SUM(od.quantity) AS total_quantity_sold
FROM order_details od
JOIN products p 
    ON od.prod_id = p.prod_id
JOIN categories c 
    ON p.cat_id = c.cat_id
JOIN supplier s 
    ON p.sup_id = s.sup_id
GROUP BY c.cat_id, c.cat_name, s.sup_id, s.sup_name
ORDER BY c.cat_name,total_quantity_sold DESC;

-- #3. Sales and Order Trends
-- 3.1 How many orders have been placed in total?
SELECT COUNT(*) as Total_orders
FROM orders;

-- 3.2 What is the average value per order?
SELECT o.ord_id,
AVG(od.total_price)
FROM orders o
JOIN order_Details od
ON o.ord_id = od.ord_id
GROUP BY o.ord_id
ORDER BY o.ord_id;

-- 3.3 On which dates were the most orders placed?
SELECT order_date,
COUNT(ord_id) AS total_orders
FROM orders
GROUP BY order_date
ORDER BY total_orders DESC;

-- 3.4 What are the monthly trends in order volume and revenue?
SELECT 
MONTH(o.order_date) AS month,
COUNT(DISTINCT o.ord_id) AS total_orders,
SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od
ON o.ord_id = od.ord_id
GROUP BY MONTH(o.order_date)
ORDER BY month;

-- 3.5 How do order patterns vary across weekdays and weekends?
SELECT 
DAYNAME(STR_TO_DATE(order_date,'%Y-%m-%d')) AS day_name,
COUNT(ord_id) AS total_orders
FROM orders
GROUP BY day_name
ORDER BY total_orders DESC;

# 4️. Supplier Contribution
-- 4.1 How many suppliers are there in the database?
SELECT COUNT(*) AS total_suppliers
FROM supplier;

-- 4.2 Which supplier provides the most products?
SELECT s.sup_name,
COUNT(p.prod_id) AS total_products
FROM supplier s
JOIN products p
ON s.sup_id = p.sup_id
GROUP BY s.sup_name
ORDER BY total_products DESC
LIMIT 1;

-- 4.3 What is the average price of products from each supplier?
SELECT s.sup_name,
AVG(p.price) AS avg_product_price
FROM supplier s
JOIN products p
ON s.sup_id = p.sup_id
GROUP BY s.sup_name
ORDER BY avg_product_price DESC;

-- 4.4 Which suppliers contribute the most to total product sales (by revenue)?
SELECT s.sup_name,
SUM(od.total_price) AS total_revenue
FROM supplier s
JOIN products p 
ON s.sup_id = p.sup_id
JOIN order_details od 
ON p.prod_id = od.prod_id
GROUP BY s.sup_name
ORDER BY total_revenue DESC;

# 5️. Employee Performance
-- 5.1  How many employees have processed orders?
SELECT COUNT(DISTINCT emp_id) AS employees_processed_orders
FROM orders;

-- 5.2 Which employees have handled the most orders?
SELECT e.emp_name,
COUNT(o.ord_id) AS total_orders
FROM employees e
JOIN orders o
ON e.emp_id = o.emp_id
GROUP BY e.emp_name
ORDER BY total_orders DESC;

-- 5.3 What is the total sales value processed by each employee?
SELECT e.emp_name,
SUM(od.total_price) AS total_sales
FROM employees e
JOIN orders o
ON e.emp_id = o.emp_id
JOIN order_details od
ON o.ord_id = od.ord_id
GROUP BY e.emp_name
ORDER BY total_sales DESC;

-- 5.4 What is the average order value handled per employee?
SELECT e.emp_name,
AVG(order_total) AS avg_order_value
FROM employees e
JOIN orders o 
ON e.emp_id = o.emp_id
JOIN (
    SELECT ord_id, SUM(total_price) AS order_total
    FROM order_details
    GROUP BY ord_id
) od
ON o.ord_id = od.ord_id
GROUP BY e.emp_name
ORDER BY avg_order_value DESC;

# 6️. Order Details Deep Dive
-- 6.1 What is the relationship between quantity ordered and total price?
SELECT quantity,
AVG(total_price) AS avg_total_price
FROM order_details
GROUP BY quantity
ORDER BY quantity; 

-- 6.2 What is the average quantity ordered per product?
SELECT p.prod_name,
AVG(od.quantity) AS avg_quantity_ordered
FROM products p
JOIN order_details od
ON p.prod_id = od.prod_id
GROUP BY p.prod_name
ORDER BY avg_quantity_ordered DESC;

-- 6.3 How does the unit price vary across products and orders?
SELECT p.prod_name,
o.ord_id,
od.each_price
FROM order_details od
JOIN products p
ON od.prod_id = p.prod_id
JOIN orders o
ON od.ord_id = o.ord_id
ORDER BY p.prod_name, od.each_price DESC;



